<?php

use Illuminate\Database\Seeder;
use App\RotacionInsumo;

class RotacionMPSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Enero 2016
        RotacionInsumo::create([
            'id_rotacion'=>1,
            'id_insumo'=>1,
            'id_mes_anio'=>1,
            'cantidad_disponible'=>59000,
            'cantidad_consumida'=>18659
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>2,
            'id_insumo'=>2,
            'id_mes_anio'=>1,
            'cantidad_disponible'=>50900,
            'cantidad_consumida'=>18659
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>3,
            'id_insumo'=>3,
            'id_mes_anio'=>1,
            'cantidad_disponible'=>58000,
            'cantidad_consumida'=>18659
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>4,
            'id_insumo'=>4,
            'id_mes_anio'=>1,
            'cantidad_disponible'=>50000,
            'cantidad_consumida'=>18659
        ]);
        
        RotacionInsumo::create([
            'id_rotacion'=>5,
            'id_insumo'=>5,
            'id_mes_anio'=>1,
            'cantidad_disponible'=>508900,
            'cantidad_consumida'=>108659
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>6,
            'id_insumo'=>6,
            'id_mes_anio'=>1,
            'cantidad_disponible'=>50000,
            'cantidad_consumida'=>18659
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>7,
            'id_insumo'=>7,
            'id_mes_anio'=>1,
            'cantidad_disponible'=>50000,
            'cantidad_consumida'=>18659
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>8,
            'id_insumo'=>8,
            'id_mes_anio'=>1,
            'cantidad_disponible'=>50000,
            'cantidad_consumida'=>18659
        ]);

        RotacionInsumo::create([
            'id_rotacion'=>9,
            'id_insumo'=>9,
            'id_mes_anio'=>1,
            'cantidad_disponible'=>50000,
            'cantidad_consumida'=>18659
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>10,
            'id_insumo'=>10,
            'id_mes_anio'=>1,
            'cantidad_disponible'=>50000,
            'cantidad_consumida'=>18659
        ]);

        // FEBRERO 2016
        RotacionInsumo::create([
            'id_rotacion'=>13,
            'id_insumo'=>1,
            'id_mes_anio'=>2,
            'cantidad_disponible'=>895478,
            'cantidad_consumida'=>49600
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>14,
            'id_insumo'=>2,
            'id_mes_anio'=>2,
            'cantidad_disponible'=>895478,
            'cantidad_consumida'=>45000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>15,
            'id_insumo'=>3,
            'id_mes_anio'=>2,
            'cantidad_disponible'=>895478,
            'cantidad_consumida'=>40000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>16,
            'id_insumo'=>4,
            'id_mes_anio'=>2,
            'cantidad_disponible'=>895478,
            'cantidad_consumida'=>45080
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>17,
            'id_insumo'=>5,
            'id_mes_anio'=>2,
            'cantidad_disponible'=>95000,
            'cantidad_consumida'=>60000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>18,
            'id_insumo'=>6,
            'id_mes_anio'=>2,
            'cantidad_disponible'=>95000,
            'cantidad_consumida'=>60000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>19,
            'id_insumo'=>7,
            'id_mes_anio'=>2,
            'cantidad_disponible'=>95000,
            'cantidad_consumida'=>60000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>20,
            'id_insumo'=>8,
            'id_mes_anio'=>2,
            'cantidad_disponible'=>95000,
            'cantidad_consumida'=>60000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>21,
            'id_insumo'=>9,
            'id_mes_anio'=>2,
            'cantidad_disponible'=>700000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>22,
            'id_insumo'=>10,
            'id_mes_anio'=>2,
            'cantidad_disponible'=>800000,
            'cantidad_consumida'=>23000
        ]);

        //MARZO 2016
        RotacionInsumo::create([
            'id_rotacion'=>25,
            'id_insumo'=>1,
            'id_mes_anio'=>3,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>26,
            'id_insumo'=>2,
            'id_mes_anio'=>3,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>27,
            'id_insumo'=>3,
            'id_mes_anio'=>3,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>28,
            'id_insumo'=>4,
            'id_mes_anio'=>3,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>29,
            'id_insumo'=>5,
            'id_mes_anio'=>3,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>30,
            'id_insumo'=>6,
            'id_mes_anio'=>3,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>31,
            'id_insumo'=>7,
            'id_mes_anio'=>3,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>32,
            'id_insumo'=>8,
            'id_mes_anio'=>3,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>33,
            'id_insumo'=>9,
            'id_mes_anio'=>3,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>34,
            'id_insumo'=>10,
            'id_mes_anio'=>3,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);


        //ABRIL 2016
        RotacionInsumo::create([
            'id_rotacion'=>35,
            'id_insumo'=>1,
            'id_mes_anio'=>4,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>36,
            'id_insumo'=>2,
            'id_mes_anio'=>4,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>37,
            'id_insumo'=>3,
            'id_mes_anio'=>4,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>38,
            'id_insumo'=>4,
            'id_mes_anio'=>4,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>39,
            'id_insumo'=>5,
            'id_mes_anio'=>4,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>40,
            'id_insumo'=>6,
            'id_mes_anio'=>4,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>41,
            'id_insumo'=>7,
            'id_mes_anio'=>4,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>42,
            'id_insumo'=>8,
            'id_mes_anio'=>4,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>43,
            'id_insumo'=>9,
            'id_mes_anio'=>4,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>44,
            'id_insumo'=>10,
            'id_mes_anio'=>4,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);

        //MAYO 2016
        RotacionInsumo::create([
            'id_rotacion'=>45,
            'id_insumo'=>1,
            'id_mes_anio'=>5,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>46,
            'id_insumo'=>2,
            'id_mes_anio'=>5,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>47,
            'id_insumo'=>3,
            'id_mes_anio'=>5,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>48,
            'id_insumo'=>4,
            'id_mes_anio'=>5,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>49,
            'id_insumo'=>5,
            'id_mes_anio'=>5,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>50,
            'id_insumo'=>6,
            'id_mes_anio'=>5,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>51,
            'id_insumo'=>7,
            'id_mes_anio'=>5,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>52,
            'id_insumo'=>8,
            'id_mes_anio'=>5,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>53,
            'id_insumo'=>9,
            'id_mes_anio'=>5,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>54,
            'id_insumo'=>10,
            'id_mes_anio'=>5,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);

        //JUNIO 2016
        RotacionInsumo::create([
            'id_rotacion'=>55,
            'id_insumo'=>1,
            'id_mes_anio'=>6,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>56,
            'id_insumo'=>2,
            'id_mes_anio'=>6,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>57,
            'id_insumo'=>3,
            'id_mes_anio'=>6,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>58,
            'id_insumo'=>4,
            'id_mes_anio'=>6,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>59,
            'id_insumo'=>5,
            'id_mes_anio'=>6,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>60,
            'id_insumo'=>6,
            'id_mes_anio'=>6,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>61,
            'id_insumo'=>7,
            'id_mes_anio'=>6,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>62,
            'id_insumo'=>8,
            'id_mes_anio'=>6,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>63,
            'id_insumo'=>9,
            'id_mes_anio'=>6,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>64,
            'id_insumo'=>10,
            'id_mes_anio'=>6,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);




        /*----------------------------------MEDIO AÑO-----------------------------------------*/
        // JULIO 2016
        RotacionInsumo::create([
            'id_rotacion'=>65,
            'id_insumo'=>1,
            'id_mes_anio'=>7,
            'cantidad_disponible'=>59000,
            'cantidad_consumida'=>18659
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>66,
            'id_insumo'=>2,
            'id_mes_anio'=>7,
            'cantidad_disponible'=>50900,
            'cantidad_consumida'=>18659
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>67,
            'id_insumo'=>3,
            'id_mes_anio'=>7,
            'cantidad_disponible'=>58000,
            'cantidad_consumida'=>18659
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>68,
            'id_insumo'=>4,
            'id_mes_anio'=>7,
            'cantidad_disponible'=>50000,
            'cantidad_consumida'=>18659
        ]);
        
        RotacionInsumo::create([
            'id_rotacion'=>69,
            'id_insumo'=>5,
            'id_mes_anio'=>7,
            'cantidad_disponible'=>508900,
            'cantidad_consumida'=>108659
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>70,
            'id_insumo'=>6,
            'id_mes_anio'=>7,
            'cantidad_disponible'=>50000,
            'cantidad_consumida'=>18659
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>71,
            'id_insumo'=>7,
            'id_mes_anio'=>7,
            'cantidad_disponible'=>50000,
            'cantidad_consumida'=>18659
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>72,
            'id_insumo'=>8,
            'id_mes_anio'=>7,
            'cantidad_disponible'=>50000,
            'cantidad_consumida'=>18659
        ]);

        RotacionInsumo::create([
            'id_rotacion'=>73,
            'id_insumo'=>9,
            'id_mes_anio'=>7,
            'cantidad_disponible'=>50000,
            'cantidad_consumida'=>18659
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>74,
            'id_insumo'=>10,
            'id_mes_anio'=>7,
            'cantidad_disponible'=>50000,
            'cantidad_consumida'=>18659
        ]);
        


        // AGOSTO 2016
        RotacionInsumo::create([
            'id_rotacion'=>77,
            'id_insumo'=>1,
            'id_mes_anio'=>8,
            'cantidad_disponible'=>895478,
            'cantidad_consumida'=>49600
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>78,
            'id_insumo'=>2,
            'id_mes_anio'=>8,
            'cantidad_disponible'=>895478,
            'cantidad_consumida'=>45000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>79,
            'id_insumo'=>3,
            'id_mes_anio'=>8,
            'cantidad_disponible'=>895478,
            'cantidad_consumida'=>40000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>80,
            'id_insumo'=>4,
            'id_mes_anio'=>8,
            'cantidad_disponible'=>895478,
            'cantidad_consumida'=>45080
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>81,
            'id_insumo'=>5,
            'id_mes_anio'=>8,
            'cantidad_disponible'=>95000,
            'cantidad_consumida'=>60000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>82,
            'id_insumo'=>6,
            'id_mes_anio'=>8,
            'cantidad_disponible'=>95000,
            'cantidad_consumida'=>60000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>83,
            'id_insumo'=>7,
            'id_mes_anio'=>8,
            'cantidad_disponible'=>95000,
            'cantidad_consumida'=>60000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>84,
            'id_insumo'=>8,
            'id_mes_anio'=>8,
            'cantidad_disponible'=>95000,
            'cantidad_consumida'=>60000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>85,
            'id_insumo'=>9,
            'id_mes_anio'=>8,
            'cantidad_disponible'=>700000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>86,
            'id_insumo'=>10,
            'id_mes_anio'=>8,
            'cantidad_disponible'=>800000,
            'cantidad_consumida'=>23000
        ]);

        //SEPTIEMBRE 2016
        RotacionInsumo::create([
            'id_rotacion'=>87,
            'id_insumo'=>1,
            'id_mes_anio'=>9,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>88,
            'id_insumo'=>2,
            'id_mes_anio'=>9,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>89,
            'id_insumo'=>3,
            'id_mes_anio'=>9,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>90,
            'id_insumo'=>4,
            'id_mes_anio'=>9,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>91,
            'id_insumo'=>5,
            'id_mes_anio'=>9,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>92,
            'id_insumo'=>6,
            'id_mes_anio'=>9,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>93,
            'id_insumo'=>7,
            'id_mes_anio'=>9,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>94,
            'id_insumo'=>8,
            'id_mes_anio'=>9,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>95,
            'id_insumo'=>9,
            'id_mes_anio'=>9,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>96,
            'id_insumo'=>10,
            'id_mes_anio'=>9,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);


        //OCTUBRE 2016
        RotacionInsumo::create([
            'id_rotacion'=>97,
            'id_insumo'=>1,
            'id_mes_anio'=>10,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>98,
            'id_insumo'=>2,
            'id_mes_anio'=>10,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>99,
            'id_insumo'=>3,
            'id_mes_anio'=>10,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>100,
            'id_insumo'=>4,
            'id_mes_anio'=>10,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>101,
            'id_insumo'=>5,
            'id_mes_anio'=>10,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>102,
            'id_insumo'=>6,
            'id_mes_anio'=>10,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>103,
            'id_insumo'=>7,
            'id_mes_anio'=>10,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>104,
            'id_insumo'=>8,
            'id_mes_anio'=>10,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>105,
            'id_insumo'=>9,
            'id_mes_anio'=>10,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>106,
            'id_insumo'=>10,
            'id_mes_anio'=>10,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);

        //NOVIEMBRE 2016
        RotacionInsumo::create([
            'id_rotacion'=>107,
            'id_insumo'=>1,
            'id_mes_anio'=>11,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>108,
            'id_insumo'=>2,
            'id_mes_anio'=>11,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>109,
            'id_insumo'=>3,
            'id_mes_anio'=>11,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>110,
            'id_insumo'=>4,
            'id_mes_anio'=>11,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>111,
            'id_insumo'=>5,
            'id_mes_anio'=>11,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>112,
            'id_insumo'=>6,
            'id_mes_anio'=>11,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>113,
            'id_insumo'=>7,
            'id_mes_anio'=>11,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>114,
            'id_insumo'=>8,
            'id_mes_anio'=>11,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>115,
            'id_insumo'=>9,
            'id_mes_anio'=>11,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>116,
            'id_insumo'=>10,
            'id_mes_anio'=>11,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);

        //DICIEMBRE 2016
        RotacionInsumo::create([
            'id_rotacion'=>117,
            'id_insumo'=>1,
            'id_mes_anio'=>12,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>118,
            'id_insumo'=>2,
            'id_mes_anio'=>12,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>119,
            'id_insumo'=>3,
            'id_mes_anio'=>12,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>120,
            'id_insumo'=>4,
            'id_mes_anio'=>12,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>121,
            'id_insumo'=>5,
            'id_mes_anio'=>12,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>122,
            'id_insumo'=>6,
            'id_mes_anio'=>12,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>123,
            'id_insumo'=>7,
            'id_mes_anio'=>12,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>124,
            'id_insumo'=>8,
            'id_mes_anio'=>12,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>125,
            'id_insumo'=>9,
            'id_mes_anio'=>12,
            'cantidad_disponible'=>400000,
            'cantidad_consumida'=>23000
        ]);
        RotacionInsumo::create([
            'id_rotacion'=>126,
            'id_insumo'=>10,
            'id_mes_anio'=>12,
            'cantidad_disponible'=>900000,
            'cantidad_consumida'=>23000
        ]);
    }
}
