<?php

use Illuminate\Database\Seeder;
use App\AnioProduccion;
use App\MesProduccion;

class YearAndMonthSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create years
        AnioProduccion::create([
            'id_anio'=>1,
            'anio'=>2016
        ]);
        AnioProduccion::create([
            'id_anio'=>2,
            'anio'=>2017
        ]);
        /*AnioProduccion::create([
            'id_anio'=>3,
            'anio'=>2018
        ]);
        AnioProduccion::create([
            'id_anio'=>4,
            'anio'=>2019
        ]);
        AnioProduccion::create([
            'id_anio'=>5,
            'anio'=>2020
        ]);*/

        //Create months of year 1
        MesProduccion::create([
            'id_mes'=>1,
            'id_anio'=>1,
            'mes'=>'Enero'
        ]);
        MesProduccion::create([
            'id_mes'=>2,
            'id_anio'=>1,
            'mes'=>'Febrero'
        ]);
        MesProduccion::create([
            'id_mes'=>3,
            'id_anio'=>1,
            'mes'=>'Marzo'
        ]);
        MesProduccion::create([
            'id_mes'=>4,
            'id_anio'=>1,
            'mes'=>'Abril'
        ]);
        MesProduccion::create([
            'id_mes'=>5,
            'id_anio'=>1,
            'mes'=>'Mayo'
        ]);
        MesProduccion::create([
            'id_mes'=>6,
            'id_anio'=>1,
            'mes'=>'Junio'
        ]);
        MesProduccion::create([
            'id_mes'=>7,
            'id_anio'=>1,
            'mes'=>'Julio'
        ]);
        MesProduccion::create([
            'id_mes'=>8,
            'id_anio'=>1,
            'mes'=>'Agosto'
        ]);
        MesProduccion::create([
            'id_mes'=>9,
            'id_anio'=>1,
            'mes'=>'Septiembre'
        ]);
        MesProduccion::create([
            'id_mes'=>10,
            'id_anio'=>1,
            'mes'=>'Octubre'
        ]);
        MesProduccion::create([
            'id_mes'=>11,
            'id_anio'=>1,
            'mes'=>'Noviembre'
        ]);
        MesProduccion::create([
            'id_mes'=>12,
            'id_anio'=>1,
            'mes'=>'Diciembre'
        ]);

        //Create months of year 2
        MesProduccion::create([
            'id_mes'=>13,
            'id_anio'=>2,
            'mes'=>'Enero'
        ]);
        MesProduccion::create([
            'id_mes'=>14,
            'id_anio'=>2,
            'mes'=>'Febrero'
        ]);
        MesProduccion::create([
            'id_mes'=>15,
            'id_anio'=>2,
            'mes'=>'Marzo'
        ]);
        MesProduccion::create([
            'id_mes'=>16,
            'id_anio'=>2,
            'mes'=>'Abril'
        ]);
        MesProduccion::create([
            'id_mes'=>17,
            'id_anio'=>2,
            'mes'=>'Mayo'
        ]);
        MesProduccion::create([
            'id_mes'=>18,
            'id_anio'=>2,
            'mes'=>'Junio'
        ]);
        MesProduccion::create([
            'id_mes'=>19,
            'id_anio'=>2,
            'mes'=>'Julio'
        ]);
        MesProduccion::create([
            'id_mes'=>20,
            'id_anio'=>2,
            'mes'=>'Agosto'
        ]);
        MesProduccion::create([
            'id_mes'=>21,
            'id_anio'=>2,
            'mes'=>'Septiembre'
        ]);
        MesProduccion::create([
            'id_mes'=>22,
            'id_anio'=>2,
            'mes'=>'Octubre'
        ]);
        MesProduccion::create([
            'id_mes'=>23,
            'id_anio'=>2,
            'mes'=>'Noviembre'
        ]);
        MesProduccion::create([
            'id_mes'=>24,
            'id_anio'=>2,
            'mes'=>'Diciembre'
        ]);
    }
}
