<?php

use Illuminate\Database\Seeder;
use App\AnioProduccion;
use App\MesProduccion;
use App\MesAnio;

class YearAndMonthSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create years
        AnioProduccion::create([
            'id_anio'=>1,
            'anio'=>2016
        ]);
        AnioProduccion::create([
            'id_anio'=>2,
            'anio'=>2017
        ]);
        AnioProduccion::create([
            'id_anio'=>3,
            'anio'=>2018
        ]);
        AnioProduccion::create([
            'id_anio'=>4,
            'anio'=>2019
        ]);
        AnioProduccion::create([
            'id_anio'=>5,
            'anio'=>2020
        ]);

        //Create months of year 1
        MesProduccion::create([
            'id_mes'=>1,
            'mes'=>'Enero'
        ]);
        MesProduccion::create([
            'id_mes'=>2,
            'mes'=>'Febrero'
        ]);
        MesProduccion::create([
            'id_mes'=>3,
            'mes'=>'Marzo'
        ]);
        MesProduccion::create([
            'id_mes'=>4,
            'mes'=>'Abril'
        ]);
        MesProduccion::create([
            'id_mes'=>5,
            'mes'=>'Mayo'
        ]);
        MesProduccion::create([
            'id_mes'=>6,
            'mes'=>'Junio'
        ]);
        MesProduccion::create([
            'id_mes'=>7,
            'mes'=>'Julio'
        ]);
        MesProduccion::create([
            'id_mes'=>8,
            'mes'=>'Agosto'
        ]);
        MesProduccion::create([
            'id_mes'=>9,
            'mes'=>'Septiembre'
        ]);
        MesProduccion::create([
            'id_mes'=>10,
            'mes'=>'Octubre'
        ]);
        MesProduccion::create([
            'id_mes'=>11,
            'mes'=>'Noviembre'
        ]);
        MesProduccion::create([
            'id_mes'=>12,
            'mes'=>'Diciembre'
        ]);


         //Create year 1 all months
         MesAnio::create([
            'id_mes'=>1,
            'id_anio'=>1,
            'id_mes_anio'=>1
        ]);
        MesAnio::create([
            'id_mes'=>2,
            'id_anio'=>1,
            'id_mes_anio'=>2
        ]);
        MesAnio::create([
            'id_mes'=>3,
            'id_anio'=>1,
            'id_mes_anio'=>3
        ]);
        MesAnio::create([
            'id_mes'=>4,
            'id_anio'=>1,
            'id_mes_anio'=>4
        ]);
        MesAnio::create([
            'id_mes'=>5,
            'id_anio'=>1,
            'id_mes_anio'=>5
        ]);
        MesAnio::create([
            'id_mes'=>6,
            'id_anio'=>1,
            'id_mes_anio'=>6
        ]);
        MesAnio::create([
            'id_mes'=>7,
            'id_anio'=>1,
            'id_mes_anio'=>7
        ]);
        MesAnio::create([
            'id_mes'=>8,
            'id_anio'=>1,
            'id_mes_anio'=>8
        ]);
        MesAnio::create([
            'id_mes'=>9,
            'id_anio'=>1,
            'id_mes_anio'=>9
        ]);
        MesAnio::create([
            'id_mes'=>10,
            'id_anio'=>1,
            'id_mes_anio'=>10
        ]);
        MesAnio::create([
            'id_mes'=>11,
            'id_anio'=>1,
            'id_mes_anio'=>11
        ]);
        MesAnio::create([
            'id_mes'=>12,
            'id_anio'=>1,
            'id_mes_anio'=>12
        ]);

        //Create year 1 all months
        MesAnio::create([
            'id_mes'=>1,
            'id_anio'=>2,
            'id_mes_anio'=>13
        ]);
        MesAnio::create([
            'id_mes'=>2,
            'id_anio'=>2,
            'id_mes_anio'=>14
        ]);
        MesAnio::create([
            'id_mes'=>3,
            'id_anio'=>2,
            'id_mes_anio'=>15
        ]);
        MesAnio::create([
            'id_mes'=>4,
            'id_anio'=>2,
            'id_mes_anio'=>16
        ]);
        MesAnio::create([
            'id_mes'=>5,
            'id_anio'=>2,
            'id_mes_anio'=>17
        ]);
        MesAnio::create([
            'id_mes'=>6,
            'id_anio'=>2,
            'id_mes_anio'=>18
        ]);
        MesAnio::create([
            'id_mes'=>7,
            'id_anio'=>2,
            'id_mes_anio'=>19
        ]);
        MesAnio::create([
            'id_mes'=>8,
            'id_anio'=>2,
            'id_mes_anio'=>20
        ]);
        MesAnio::create([
            'id_mes'=>9,
            'id_anio'=>2,
            'id_mes_anio'=>21
        ]);
        MesAnio::create([
            'id_mes'=>10,
            'id_anio'=>2,
            'id_mes_anio'=>22
        ]);
        MesAnio::create([
            'id_mes'=>11,
            'id_anio'=>2,
            'id_mes_anio'=>23
        ]);
        MesAnio::create([
            'id_mes'=>12,
            'id_anio'=>2,
            'id_mes_anio'=>24
        ]);
    }
}
